const GameData = {

    // Debug-Modus
    debug: false, // Auf false setzen für Produktionsversion

    // Spieler-Informationen
    player: {
        inventory: [],
        progress: {
            hasSeenIntro: true,
        }
    },

    // Viewport-Einstellungen für das Design, angepasst an Hintergrundbild
    viewport: {
        width: 1792,  // Referenzbreite passend zum Hintergrundbild
        height: 1024, // Referenzhöhe passend zum Hintergrundbild
    },

    // Konstanten für die Skalierung, etc.
    constants: {
        sophieScale: 0.37,
        busScale: 1.28,
        textScale: 1.5,
        dialogSpeed: 30, // Textverzögerung in ms
        walkSpeed: 200,  // Gehgeschwindigkeit
        hoverTextFontSize: 18, // Standardgröße für Hover-Texte
        hoverTextPadding: { x: 8, y: 4 } // Standard-Padding für Hover-Texte
    },

    // Gemeinsame Assets, die in allen Szenen verwendet werden können
    commonAssets: [
        { type: 'spritesheet', key: 'sophie', path: 'assets/images/character_sophie.png', frameConfig: { frameWidth: 164, frameHeight: 488 } },
        { type: 'image', key: 'bag_open', path: 'assets/images/controls_bag_open.png' },
        { type: 'image', key: 'bag_closed', path: 'assets/images/controls_bag_closed.png' },

        // inventory assets
        { type: 'image', key: 'invMagnet', path: 'assets/images/inv_magnet.png' },
        { type: 'image', key: 'invCatNotice', path: 'assets/images/inv_cat_notice.png' },
        { type: 'image', key: 'invCoin', path: 'assets/images/inv_coin.png' },
        { type: 'image', key: 'invEmptyToiletPaperRole', path: 'assets/images/inv_empty_toilet_paper_role.png' },
        { type: 'image', key: 'invSprayCan', path: 'assets/images/inv_spray_can.png' },
        { type: 'image', key: 'invAccessForm', path: 'assets/images/inv_access_form.png' },
        { type: 'image', key: 'invAccessCard', path: 'assets/images/inv_access_card.png' },
        { type: 'image', key: 'invGummyBears', path: 'assets/images/inv_gummy_bears.png' },
        { type: 'image', key: 'invScrumGuide', path: 'assets/images/inv_scrum_guide.png' },
        { type: 'image', key: 'invPen', path: 'assets/images/inv_pen.png' },
        { type: 'image', key: 'invCokeClosed', path: 'assets/images/inv_coke_closed.png' },
        { type: 'image', key: 'invCokeBomb', path: 'assets/images/inv_coke_closed.png' },
        { type: 'image', key: 'invCokeOpen', path: 'assets/images/inv_coke_open.png' },
        { type: 'image', key: 'invBottleOpener', path: 'assets/images/inv_bottle_opener.png' },
        { type: 'image', key: 'invBusinessCards', path: 'assets/images/inv_business_cards.png' },
        { type: 'image', key: 'invManifest', path: 'assets/images/inv_manifest.png' },


    ],

    // Interaktive Objekte - Nach Szenen organisiert
    scenes: {
        ThemeScene: {
            background: 'theme',
            assets: [
                { type: 'image', key: 'theme', path: 'assets/images/theme.webp' },
                { type: 'image', key: 'logo', path: 'assets/images/theme_logo.svg' }
            ],
            interactiveObjects: [],
            hideSophie: true,
        },

        // Intro-Szene hat keine interaktiven Objekte
        IntroScene: {
            background: 'building_intro',
            sophieBottomPosition: 0.975,
            assets: [
                { type: 'image', key: 'building_intro', path: 'assets/images/building_intro.webp' },
                { type: 'image', key: 'bus', path: 'assets/images/intro_bus.png' }
            ],
            interactiveObjects: []
        },

        // Gebäude-Szene mit Bushaltestelle
        BuildingScene: {
            background: 'building',
            sophieBottomPosition: 0.975,
            assets: [
                { type: 'image', key: 'building', path: 'assets/images/building.webp' },
                { type: 'image', key: 'lanternNotice', path: 'assets/images/building_lantern_notice.png' },
                { type: 'image', key: 'trash', path: 'assets/images/building_trash.png' }
            ],
            interactiveObjects: [
                {
                    id: 'advertisingPoster',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.29,
                    relativeY: 0.85,
                    relativeWidth: 0.065,
                    relativeHeight: 0.15,
                    hoverText: "Werbeplakat",
                    debug: true,
                    depth: 10,
                    view: ['Werbung:', '"Fraxicle Inc. - Wir lassen Träume wahr werden!"', "Es bleibt absolut unklar, womit diese Firma Geld verdient."],
                    take: ["Das ist sicherlich wichtig für das Marketing von Fraxicle.", "Als Agile Coach will ich den direkten Kontakt mit dem Kunden nicht beeinträchtigen."]
                },
                {
                    id: 'busStop',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.76,
                    relativeY: 0.88,
                    relativeWidth: 0.14,
                    relativeHeight: 0.18,
                    hoverText: "Bushaltestelle",
                    debug: true,
                    depth: 10,
                    view: ["Commerce Center A, Springfield, Ohio.", "Der nächste Bus kommt erst in 9 Stunden."],
                    take: ["Das ist eine öffentliche Einrichtung.", "Ich lasse sie besser hier."]
                },
                {
                    id: 'lanternNotice',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'lanternNotice',
                    relativeX: 0.883,
                    relativeY: 0.834,
                    relativeWidth: 0.012,
                    relativeHeight: 0.04,
                    hoverText: "Zettel",
                    debug: true,
                    depth: 10,
                    view: ["Katze Mimi ist entlaufen.", "Der Zettel ist schon ein paar Jahre alt.","Arme Katze Mimi.","Am Zettel ist ein Magnet."],
                    take: ["Den Magneten nehme ich auch mit.", "Wie auch immer der auf dem Holzmast haften konnte ¯\\_(ツ)_/¯"],
                    removable: true,
                    removeSound: "FLUP",
                    inventoryAssets: ['invCatNotice', 'invMagnet']
                },
                {
                    id: 'trashBins',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.383,
                    relativeY: 0.929,
                    relativeWidth: 0.082,
                    relativeHeight: 0.085,
                    hoverText: "Mülleimer",
                    exactPositioning: true,
                    debug: true,
                    depth: 11,
                    sophieViewFrame: "back",
                    viewSound: "RUMPELRUMPEL",
                    view: ["Einiges davon könnte nützlich sein.", "Aber ich bin mir nicht sicher ob ich ausreichend Commitment habe, den Müll mitzunehmen."],
                    viewOnlyOnce: true,
                    take: ["Die sind sehr groß und voller Müll und bleiben genau dort wo sie sind."],
                },
                {
                    id: 'trash',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'trash',
                    relativeX: 0.41,
                    relativeY: 0.905,
                    relativeWidth: 0.012,
                    relativeHeight: 0.04,
                    hoverText: "Müll",
                    debug: true,
                    depth: 10,
                    view: ["Alle was ich als fest und kompakt identifizieren konnte."],
                    preTake: ["Ich kann nicht fassen, dass ich das hier wirklich tue.", "Ich werde das der Gewerkschaft melden.", "Ich fordere bessere Arbeitsbedingungen für uns Agile Coaches!"],
                    take: ["Na was haben wir denn hier:","Ein Spraydose Farbe RAL 9016 - Verkehrsweiß.", "Eine Münze.", "Und eine leere Rolle Klopapier.", "IGITTTT!!!" ],
                    removable: true,
                    inventoryAssets: ['invCoin', 'invSprayCan', 'invEmptyToiletPaperRole']
                },
                {
                    id: 'strangeWindow',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.494,
                    relativeY: 0.27,
                    relativeWidth: 0.014,
                    relativeHeight: 0.05,
                    hoverText: "Auffälliges Fenster",
                    debug: true,
                    depth: 10,
                    view: ["Könnte ein Meetingraum sein.", "Ich kann von hier unten die Details nicht erkennen.", "Ich bräuchte etwas, durch das ich hindurchsehen kann."],
                    sophieViewFrame: "back",
                    preTake: ["Agiler Wahnsinn oder was?"],
                    take: ["Ich kletter da jetzt auf keinen Fall rauf."],
                    sophieTakeFrame: "back"
                },
                {
                    id: 'officeEntry',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.52,
                    relativeY: 0.82,
                    relativeWidth: 0.1,
                    relativeHeight: 0.11,
                    hoverText: "Eingang zur Lobby",
                    debug: true,
                    depth: 10,
                    view: ["Ohne Zweifel der Eingang zu diesem auffällig geformten Gebäude."],
                    take: ["Es heißt nicht ohne Grund Im-mo-bi-li-e."]
                },
            ]
        },

        LobbyScene: {
            background: 'lobby',
            sophieScale: 0.55,
            sophieBottomPosition: 0.83,
            kenMonologOffset: -0.03,
            leftBoundary: 0.11,
            rightBoundary: 0.91,
            monologOffset: 0.11,
            assets: [
                { type: 'image', key: 'lobby', path: 'assets/images/lobby.webp' },
                { type: 'image', key: 'lobbyDesk', path: 'assets/images/lobby_desk.png' },
                { type: 'image', key: 'lobby_elevator_bg', path: 'assets/images/lobby_elevator_bg.png' },
                { type: 'image', key: 'lobby_elevator_dore_left', path: 'assets/images/lobby_elevator_dore_left.png' },
                { type: 'image', key: 'lobby_elevator_dore_right', path: 'assets/images/lobby_elevator_dore_right.png' },
                { type: 'spritesheet', key: 'ken', path: 'assets/images/character_ken.png', frameConfig: { frameWidth: 360, frameHeight: 1024 } },
                { type: 'image', key: 'kenSign', path: 'assets/images/lobby_ken_sign.png' },
            ],
            interactiveObjects: [
                {
                    id: 'lobbyExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.525,
                    relativeY: 0.37,
                    relativeWidth: 0.073,
                    relativeHeight: 0.16,
                    hoverText: "Ausgang",
                    debug: true,
                    depth: 12,
                    view: ["Da geht es wieder nach draußen."],
                    sophieViewFrame: 'walk_right',
                    viewY: 0.37,
                    take: ["Wenn ich das wegnehmen, dann sind wir hier alle für immer gefangen."],
                    removable: false,
                },
                {
                    id: 'lobbyKen',
                    defaultAction: 3,
                    type: 'rectangle',
                    relativeX: 0.558,
                    relativeY: 0.58,
                    relativeWidth: 0.045,
                    relativeHeight: 0.1,
                    hoverText: "Ken",
                    hoverXOffset: 0,
                    hoverYOffset: -0.008,
                    debug: true,
                    depth: 10,
                    view: ["Ein Merksatz:", "\"Der Empfang spiegelt die Unternehmenskultur.\"", "Ken sieht sehr beschäftigt aus."],
                    sophieViewFrame: 'walk_right',
                    viewY: 0.335,
                    take: ["Den lass ich lieber hier."],
                    removable: false,
                },
                {
                    id: 'accessControl',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.915,
                    relativeY: 0.635,
                    relativeWidth: 0.03,
                    relativeHeight: 0.1,
                    hoverYOffset: -0.0085,
                    hoverText: "Zugangskontrolle",
                    debug: true,
                    depth: 10,
                    view: ["Es scheint den Fahrstuhl frei zu geben."],
                    take: ["Ich will an meinem ersten Arbeitstag nicht unangenehm auffallen."],
                    removable: false,
                },
                {
                    id: 'kenSign',
                    defaultAction: 1,
                    type: 'image',
                    texture: 'kenSign',
                    relativeX: 0.453,
                    relativeY: 0.618,
                    relativeWidth: 0.01,
                    relativeHeight: 0.01,
                    scaleFactor: 0.15,
                    hoverText: "Schild",
                    hoverYOffset: -0.02,
                    debug: true,
                    depth: 13,
                    view: ["Das steht \"Ken S.\"", "Es muss sich um einen Zufall handeln.", "Aber die Ähnlichkeit ist frappierend."],
                    take: ["Ich denke Ken wird böse, wenn ich das wegnehmen." ],
                    removable: false,
                },
                {
                    id: 'elevator',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.86,
                    relativeY: 0.63,
                    relativeWidth: 0.06,
                    relativeHeight: 0.3,
                    hoverXOffset: 0.006,
                    hoverYOffset: 0.03,
                    hoverText: "Aufzug",
                    debug: true,
                    depth: 10,
                    view: ["Der Zugang zum Bürogebäude."],
                    take: ["Er ist hier fest eingebaut."],
                    removable: false,
                },
            ],
        },

        ElevatorScene: {
            background: 'elevator',
            sophieScale: 1.1,
            sophieBottomPosition: 0.95,
            leftBoundary: 0.3,
            rightBoundary: 0.71,
            monologOffset: 0.11,
            assets: [
                {type: 'image', key: 'elevator', path: 'assets/images/elevator.png'},
                {type: 'image', key: 'manifest', path: 'assets/images/elevator_manifest.png'},
                {type: 'image', key: 'elevator_dore_bg', path: 'assets/images/elevator_dore_bg.png'},
                {type: 'image', key: 'elevator_dore_left', path: 'assets/images/elevator_dore_left.png'},
                {type: 'image', key: 'elevator_dore_right', path: 'assets/images/elevator_dore_right.png'},
            ],
            interactiveObjects: [
                {
                    id: 'controlPanel',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.265,
                    relativeY: 0.5,
                    relativeWidth: 0.095,
                    relativeHeight: 0.7,
                    hoverYOffset: 0.08,
                    hoverText: "Aufzugkontrolle",
                    debug: true,
                    depth: 10,
                    view: ["Damit kann man sagen, in welche Etage der Fahrstuhl fährt."],
                    take: ["Es ist untrennbar mit dem Aufzug verbunden."],
                    removable: false,
                },
                {
                    id: 'manifest',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'manifest',
                    relativeX: 0.765,
                    relativeY: 0.45,
                    relativeWidth: 0.012,
                    relativeHeight: 0.3,
                    hoverText: "Arbeitermanifest",
                    debug: true,
                    depth: 10,
                    view: ["Ein Aufruf zur ARBEITERREVOLUTION!!!", "Es werden besserer Arbeitsbedingungen für Mitarbeiter gefordert.", "Man kann mitmachen eine Gewerkschaft zu gründen."],
                    preTake: ["Ein Aufruf zur ARBEITERREVOLUTION!!!", "Es werden besserer Arbeitsbedingungen für Mitarbeiter gefordert.", "Man kann mitmachen eine Gewerkschaft zu gründen."],
                    take: ["Den Magneten nehme ich auch mit."],
                    removable: true,
                    removeSound: "FLUP",
                    inventoryAssets: ['invManifest', 'invMagnet']
                },
                {
                    id: 'elevatorExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.5,
                    relativeY: 0.55,
                    relativeWidth: 0.15,
                    relativeHeight: 0.55,
                    hoverYOffset: 0.08,
                    hoverText: "Ausgang",
                    debug: true,
                    depth: 10,
                    view: ["Der Weg aus dem Aufzug."],
                    take: ["Da ist nichts, was ich nehmen könnte."],
                    removable: false,
                },
            ],
        },


        MeetingScene: {
            background: 'meeting',
            sophieScale: 0.9,
            sophieFixedFrame: 'back',
            sophieBottomPosition: 0.997,
            leftBoundary: 0.433,
            rightBoundary: 0.57,
            monologOffset: 0.05,
            assets: [
                {type: 'image', key: 'meeting', path: 'assets/images/meeting.png'},
                {type: 'image', key: 'meetingChair', path: 'assets/images/meeting_chair.png'},
                {type: 'image', key: 'meetingCoke', path: 'assets/images/meeting_coke.png'},
                {type: 'image', key: 'meetingGummyBears', path: 'assets/images/meeting_gummy_bears.png'},
                {type: 'image', key: 'meetingManagers', path: 'assets/images/meeting_managers.png'},
                {type: 'image', key: 'meetingBusinessCards', path: 'assets/images/meeting_business_cards.png'},
                {type: 'image', key: 'meetingBusinessCardA', path: 'assets/images/meeting_business_card.png'},
                {type: 'image', key: 'meetingBusinessCardB', path: 'assets/images/meeting_business_card.png'},
                {type: 'image', key: 'meetingBusinessCardC', path: 'assets/images/meeting_business_card.png'},

            ],
            interactiveObjects: [
                {
                    id: 'meetingExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.8,
                    relativeY: 0.445,
                    relativeWidth: 0.11,
                    relativeHeight: 0.34,
                    hoverYOffset: 0.08,
                    hoverText: "Ausgang",
                    debug: true,
                    depth: 10,
                    view: ["Das ist der Fluchtweg aus diesem Meeting."],
                    take: ["Die Glastür möchte ich nicht die ganze Zeit mit mir tragen."],
                    removable: false,
                },
                {
                    id: 'meetingCoke',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'meetingCoke',
                    relativeX: 0.44,
                    relativeY: 0.68,
                    relativeWidth: 0.01,
                    relativeHeight: 0.15,
                    hoverText: "Cola",
                    debug: true,
                    depth: 30,
                    view: ["Eine Flasche Cola mit extra viel Zucker."],
                    removable: true,
                    inventoryAssets: ['invCokeClosed']
                },
                {
                    id: 'meetingGummyBears',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'meetingGummyBears',
                    relativeX: 0.59,
                    relativeY: 0.72,
                    relativeWidth: 0.01,
                    relativeHeight: 0.09,
                    hoverText: "Gummibären",
                    debug: true,
                    depth: 10,
                    view: ["Eine Tüte voller Gummibären.", "Gummibären erhöhen die Motivation drastisch."],
                    removable: true,
                    inventoryAssets: ['invGummyBears']
                },
                {
                    id: 'meetingBusinessCards',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'meetingBusinessCards',
                    relativeX: 0.52,
                    relativeY: 0.69,
                    relativeWidth: 0.01,
                    relativeHeight: 0.09,
                    hoverText: "Visitenkarten",
                    hoverYOffset: 0.013,
                    debug: true,
                    depth: 20,
                    view: ["Ein Stapel Visitenkarten."],
                    removable: true,
                    inventoryAssets: ['invBusinessCards', 'invBusinessCards', 'invBusinessCards']
                },
                {
                    id: 'managersA',
                    defaultAction: 3,
                    combinedKey: 'managers',
                    type: 'rectangle',
                    relativeX: 0.335,
                    relativeY: 0.6,
                    relativeWidth: 0.1,
                    relativeHeight: 0.2,
                    hoverXOffset: 0.1,
                    hoverYOffset: 0.1,
                    hoverText: "Beschäftigte Manager",
                    debug: true,
                    depth: 10,
                    view: ["Sie scheinen in einem wichtigen Thema vertieft zu sein."],
                    take: ["Sie würden sich mit Händen und Füßen dagegen wehren."],
                    removable: false,
                },
                {
                    id: 'managersB',
                    defaultAction: 3,
                    combinedKey: 'managers',
                    type: 'rectangle',
                    relativeX: 0.45,
                    relativeY: 0.52,
                    relativeWidth: 0.17,
                    relativeHeight: 0.12,
                    hoverXOffset: 0.04,
                    hoverYOffset: 0.11,
                    hoverText: "Beschäftigte Manager",
                    debug: true,
                    depth: 10,
                    view: ["Ich habe den Eindruck das Meeting dreht sich im Kreis."],
                    take: ["Sie würden sich mit Händen und Füßen dagegen wehren."],
                    removable: false,
                },
                {
                    id: 'managersC',
                    defaultAction: 3,
                    combinedKey: 'managers',
                    type: 'rectangle',
                    relativeX: 0.6,
                    relativeY: 0.56,
                    relativeWidth: 0.16,
                    relativeHeight: 0.18,
                    hoverXOffset: -0.04,
                    hoverYOffset: 0.1,
                    hoverText: "Beschäftigte Manager",
                    debug: true,
                    depth: 10,
                    view: ["Sie sehen wichtig und beschäftigt aus."],
                    take: ["Sie würden sich mit Händen und Füßen dagegen wehren."],
                    removable: false,
                },
            ],
        },

        LoungeScene: {
            background: 'lounge',
            sophieScale: 0.87,
            sophieBottomPosition: 0.93,
            leftBoundary: 0.05,
            rightBoundary: 0.95,
            monologOffset: 0.11,
            assets: [
                {type: 'image', key: 'lounge', path: 'assets/images/lounge.png'},
                {type: 'image', key: 'loungeShaker', path: 'assets/images/lounge_shaker.png'},
                {type: 'image', key: 'loungeCoke', path: 'assets/images/inv_coke_closed.png' },
                {type: 'image', key: 'loungeBottleOpener', path: 'assets/images/lounge_bottle_opener.png' },

            ],
            interactiveObjects: [
                {
                    id: 'loungeExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.95,
                    relativeY: 0.6,
                    relativeWidth: 0.12,
                    relativeHeight: 0.5,
                    hoverYOffset: 0.18,
                    hoverXOffset: 0.015,
                    hoverText: "Aufzug",
                    debug: true,
                    depth: 10,
                    view: ["Hier geht es zum Aufzug."],
                    take: ["Es ist eher immateriell."],
                    removable: false,
                },
                {
                    id: 'meetingRoomEntry',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.451 ,
                    relativeY: 0.6,
                    relativeWidth: 0.23,
                    relativeHeight: 0.2 ,
                    hoverYOffset: -0.035,
                    hoverText: "Durchgang zum Meeting in Ernie & Bert",
                    debug: true,
                    depth: 10,
                    view: ["Das ist der Eingang zum Meetingraum."],
                    take: ["Das lass ich genau da wo es ist."],
                    removable: false,
                },
                {
                    id: 'milkShaker',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.67,
                    relativeY: 0.7,
                    relativeWidth: 0.08,
                    relativeHeight: 0.4,
                    hoverYOffset: 0.001,
                    hoverText: "Milchshaker",
                    debug: true,
                    depth: 10,
                    view: ["Man tut eine Flasche Milch hinein und dann wird sie zum Shake."],
                    take: ["Ich soll nicht to schwer heben."],
                    removable: false,
                },
                {
                    id: 'loungeBottleOpener',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'loungeBottleOpener',
                    relativeX: 0.1615,
                    relativeY: 0.8012,
                    relativeWidth: 0.01,
                    relativeHeight: 0.04,
                    hoverText: "Flaschenöffner",
                    debug: true,
                    depth: 10,
                    view: ["Damit kann man Flaschen öffnen."],
                    removable: true,
                    inventoryAssets: ['invBottleOpener']
                },
            ],
        },

        CEOOfficeScene: {
            background: 'ceoOffice',
            sophieScale: 0.7,
            sophieBottomPosition: 0.665,
            leftBoundary: 0.19,
            rightBoundary: 0.75,
            monologOffset: 0.11,
            assets: [
                {type: 'image', key: 'ceoOffice', path: 'assets/images/ceo_office.png'},
                {type: 'image', key: 'ceoOfficeFront', path: 'assets/images/ceo_office_front.png'},
                { type: 'spritesheet', key: 'noel', path: 'assets/images/character_noel.png', frameConfig: { frameWidth: 350, frameHeight: 834 } },
            ],
            interactiveObjects: [
                {
                    id: 'officeExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.21,
                    relativeY: 0.44,
                    relativeWidth: 0.08,
                    relativeHeight: 0.4,
                    hoverText: "Aufzug",
                    debug: true,
                    depth: 10,
                    view: ["Der Aufzug mit dem ich hier hergekommen bin."],
                    take: ["Ich will hier einen guten Eindruck hinterlassen und besser keinen Schaden anrichten ."],
                    removable: false,
                },
                {
                    id: 'officeNoel',
                    defaultAction: 3,
                    type: 'rectangle',
                    relativeX: 0.85,
                    relativeY: 0.497,
                    relativeWidth: 0.057,
                    relativeHeight: 0.34,
                    hoverText: "Noel",
                    hoverYOffset: 0.003,
                    debug: true,
                    depth: 10,
                    view: ["Offenbar die CEO dieser Organisation.", "Sie scheint eine wichtige Rede zu üben."],
                    sophieViewFrame: 'walk_right',
                    viewY: 0.7,
                    take: ["Ich will sie nicht unnötig verärgern.", "Ich fürchte die Konsequenzen."],
                    removable: false,
                },
                {
                    id: 'officeMagnet',
                    defaultAction: 2,
                    type: 'rectangle',
                    relativeX: 0.64,
                    relativeY: 0.58,
                    hoverYOffset: -0.02,
                    relativeWidth: 0.023,
                    relativeHeight: 0.035,
                    hoverText: "Magnet",
                    debug: true,
                    depth: 100000,
                    view: ["Da liegt ein Magnet."],
                    removable: true,
                    inventoryAssets: ['invMagnet']
                },
            ],
        },



        BasementScene: {
            background: 'basement',
            sophieScale: 1.1,
            sophieBottomPosition: 0.965,
            leftBoundary: 0.58,
            monologOffset: 0.03,
            assets: [
                {type: 'image', key: 'basement', path: 'assets/images/basement.png'},
                {type: 'image', key: 'basementFrontRight', path: 'assets/images/basement_front_right.png'},
                {type: 'image', key: 'basementFrontLeft', path: 'assets/images/basement_front_left.png'},
                {type: 'image', key: 'basementToiletDore', path: 'assets/images/basement_toilet_dore.png'},
                { type: 'spritesheet', key: 'jeff', path: 'assets/images/character_jeff.png', frameConfig: { frameWidth: 400, frameHeight: 892 } },
                { type: 'image', key: 'jeffSign', path: 'assets/images/basement_jeff_sign.png' },
                { type: 'image', key: 'basementCoin', path: 'assets/images/basement_coin.png' },
            ],
            interactiveObjects: [
                {
                    id: 'basementExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.95,
                    relativeY: 0.55,
                    relativeWidth: 0.1,
                    relativeHeight: 0.8,
                    hoverYOffset: 0.18,
                    hoverXOffset: -0.015,
                    hoverText: "Weg zum Aufzug",
                    debug: true,
                    depth: 10,
                    view: ["Hier geht es zum Aufzug."],
                    take: ["Es ist eher immateriell."],
                    removable: false,
                },
                {
                    id: 'jeffSign',
                    defaultAction: 1,
                    type: 'image',
                    texture: 'jeffSign',
                    relativeX: 0.525,
                    relativeY: 0.645,
                    relativeWidth: 0.01,
                    relativeHeight: 0.01,
                    scaleFactor: 1,
                    hoverText: "Schild",
                    hoverYOffset: -0.03,
                    debug: true,
                    depth: 20,
                    view: ["Das steht \"Jeff S.\"", "Es muss sich um einen Zufall handeln.", "Aber die Ähnlichkeit ist frappierend."],
                    take: ["Ich denke Jeff wird böse, wenn ich es wegnehmen." ],
                    removable: false,
                },
                {
                    id: 'basementPlate',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.534,
                    relativeY: 0.69,
                    relativeWidth: 0.056,
                    relativeHeight: 0.05,
                    hoverYOffset: 0.075,
                    hoverText: "Teller",
                    debug: true,
                    depth: 20,
                    view: ["Die analoge Variante eines Kassensystems."],
                    take: ["Es ist die Grundlage für Jeffs Geschäftsmodell.", "Ich lasse es da wo es ist."],
                    removable: false,
                },
                {
                    id: 'basementTeamRoom',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.532,
                    relativeY: 0.47,
                    relativeWidth: 0.12,
                    relativeHeight: 0.37,
                    hoverYOffset: 0.07,
                    hoverText: "Tür zum Teamraum",
                    debug: true,
                    depth: 10,
                    view: ["Die Tür führt zum Raum vom Team ALOHA."],
                    take: ["Wenn ich das wegnehme, wäre das Team hier gefangen."],
                    removable: false,
                },
                {
                    id: 'basementJeff',
                    defaultAction: 3,
                    type: 'rectangle',
                    relativeX: 0.445,
                    relativeY: 0.71,
                    relativeWidth: 0.12,
                    relativeHeight: 0.534,
                    hoverText: "Jeff",
                    hoverXOffset: -0.007,
                    hoverYOffset: -0.006,
                    debug: true,
                    depth: 9,
                    view: ["Jeff managed diese Organisation bottom-up."],
                    take: ["Er sieht so friedlich aus.", "Ich lasse ihn genau da wo er ist."],
                    removable: false,
                },
                {
                    id: 'basementCoin',
                    defaultAction: 2,
                    type: 'image',
                    texture: 'basementCoin',
                    relativeX: 0.535,
                    relativeY: 0.687,
                    relativeWidth: 0.01,
                    relativeHeight: 0.01,
                    scaleFactor: 1,
                    hoverText: "Münze",
                    hoverYOffset: -0.01,
                    debug: true,
                    depth: 21,
                    view: ["Das ist der Bitcoin, den ich dort hingelegt habe."],
                    removable: true,
                    inventoryAssets: ['invCoin'],
                },
                {
                    id: 'toiletDore',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.73,
                    relativeY: 0.53,
                    relativeWidth: 0.07,
                    relativeHeight: 0.53,
                    hoverYOffset: 0.08,
                    hoverText: "Toilette",
                    debug: true,
                    depth: 10,
                    view: ["Hier geht es zur Toilette."],
                    take: ["Dafür ist meine Tasche zu klein."],
                    removable: false,
                },
            ],
        },


        TeamScene: {
            background: 'team',
            sophieScale: 0.95,
            sophieBottomPosition: 0.97,
            monologOffset: 0.03,
            assets: [
                {type: 'image', key: 'team', path: 'assets/images/team.png'},
                {type: 'image', key: 'teamFront', path: 'assets/images/team_front.png'},
                {type: 'image', key: 'teamWB20', path: 'assets/images/team_wb_20.png'},
                {type: 'image', key: 'teamWB30', path: 'assets/images/team_wb_30.png'},
                {type: 'image', key: 'teamWB40', path: 'assets/images/team_wb_40.png'},
                {type: 'image', key: 'teamWB50', path: 'assets/images/team_wb_50.png'},
                {type: 'image', key: 'teamWB60', path: 'assets/images/team_wb_60.png'},
                {type: 'image', key: 'teamWB70', path: 'assets/images/team_wb_70.png'},
                {type: 'image', key: 'teamWB80', path: 'assets/images/team_wb_80.png'},
                {type: 'image', key: 'teamWB90', path: 'assets/images/team_wb_90.png'},
                {type: 'image', key: 'teamWB100', path: 'assets/images/team_wb_100.png'},
                {type: 'image', key: 'teamScrumGuide', path: 'assets/images/team_scrum_guide.png'},
            ],
            interactiveObjects: [
                {
                    id: 'teamExit',
                    defaultAction: 4,
                    type: 'rectangle',
                    relativeX: 0.97,
                    relativeY: 0.55,
                    relativeWidth: 0.06,
                    relativeHeight: 0.8,
                    hoverYOffset: 0.18,
                    hoverXOffset: -0.015,
                    hoverText: "Ausgang",
                    debug: true,
                    depth: 10,
                    view: ["Hier geht es aus dem Teamraum heraus."],
                    take: ["Es lässt sich nicht bewegen."],
                    removable: false,
                },
                {
                    id: 'devA',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.14,
                    relativeY: 0.758,
                    relativeWidth: 0.1,
                    relativeHeight: 0.35,
                    hoverXOffset: 0.08,
                    hoverYOffset: 0,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devB',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.22,
                    relativeY: 0.44,
                    relativeWidth: 0.09,
                    relativeHeight: 0.3,
                    hoverXOffset: 0.05,
                    hoverYOffset: 0.2,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devC',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.467,
                    relativeY: 0.71,
                    relativeWidth: 0.075,
                    relativeHeight: 0.345,
                    hoverXOffset: -0.02,
                    hoverYOffset: -0.01,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devD',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.545,
                    relativeY: 0.53,
                    relativeWidth: 0.078,
                    relativeHeight: 0.33,
                    hoverXOffset: 0,
                    hoverYOffset: 0.15,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devE',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.61,
                    relativeY: 0.74,
                    relativeWidth: 0.088,
                    relativeHeight: 0.32,
                    hoverXOffset: -0.02,
                    hoverYOffset: -0.01,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devF',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.758,
                    relativeY: 0.437,
                    relativeWidth: 0.1,
                    relativeHeight: 0.29,
                    hoverXOffset: 0,
                    hoverYOffset: 0.22,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'devG',
                    defaultAction: 3,
                    combinedKey: 'devs',
                    type: 'rectangle',
                    relativeX: 0.88,
                    relativeY: 0.735,
                    relativeWidth: 0.1,
                    relativeHeight: 0.31,
                    hoverXOffset: -0.02,
                    hoverYOffset: -0.01,
                    hoverText: "Entwicklerteam",
                    debug: true,
                    depth: 10,
                    view: ["Die Mitglieder des Teams ALOHA."],
                    take: ["Das wäre ein Eingriff in ihre Autonomie als Team."],
                    removable: false,
                },
                {
                    id: 'teamBlackBoard',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.425,
                    relativeY: 0.315,
                    relativeWidth: 0.16,
                    relativeHeight: 0.2,
                    hoverText: "Blackboard",
                    debug: true,
                    depth: 10,
                    view: ["Es ist eine alte Kreidetafel.", "Damit kann man nicht agile arbeiten."],
                    take: ["Es ist an der Wand fixiert."],
                    removable: false,
                },
                {
                    id: 'teamWhiteBoard',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.425,
                    relativeY: 0.315,
                    relativeWidth: 0.16,
                    relativeHeight: 0.2,
                    hoverText: "Whiteboard",
                    debug: true,
                    depth: 11,
                    view: ["Es ist eine Whiteboard.", "Damit kann man agile arbeiten."],
                    take: ["Es ist an der Wand fixiert."],
                    removable: false,
                },
                {
                    id: 'teamTableLeg',
                    defaultAction: 1,
                    type: 'rectangle',
                    relativeX: 0.06,
                    relativeY: 0.83,
                    relativeWidth: 0.017,
                    relativeHeight: 0.15,
                    hoverText: "Tischbein",
                    debug: true,
                    depth: 11,
                    view: ["Es scheint, als würde der Tisch etwas wackeln."],
                    take: ["Es wird noch benötigt."],
                    removable: false,
                },
            ],
        },

        OutroScene: {
            background: 'outro',
            hideSophie: true,
            sophieBottomPosition: 0.97,
            assets: [
                {type: 'image', key: 'outro', path: 'assets/images/outro.png'},
            ],
            interactiveObjects: [],
        },


    },


    // Monologe
    monologs: {
        intro: [
            "Ich bin Sophie Plaice.",
            "Ich will die größte Agile Coachin aller Zeiten werden.",
            "MÖGEN DIE SPIELE BEGINNEN!!!",
            "Ähm.",
            "Da ist mein Temperament wohl etwas mit mir durchgegangen.",
            "Lass uns einfach anfangen."
        ]
    },

    inventoryItems: [
        {key: 'invCokeClosed', title: 'Cola', show: false, view: ["Eine Flasche Coke."]},
        {key: 'invCokeBomb', title: 'Coke-Bombe', show: false, view: ["Eine stark geschüttelte Flasche Cola."]},
        {key: 'invAccessForm', title: 'Formular', show: false, view: ["Damit ich reinkomme, muss ich ...", "... es von jemandem ausfüllen lassen, ...", "... der drin ist.", "Ein absolut sinnloses Formular."]},
        {key: 'invGummyBears', title: 'Gummibären', show: false, view: ["Eine Tüte leckerer Gummibären.", "Sie sind vegan und es musste kein Bär dafür sterben."]},
        {key: 'invEmptyToiletPaperRole', title: 'Klorolle', show: false, view: ["Eine leere Papierrolle.", "Ich spreche nicht darüber, wo ich sie her habe."]},
        {key: 'invMagnet', title: 'Magnet', titlePlural: 'Magnete', show: false, view: ["Scheinbar magnetisch.", "Ich könnte stundenlang damit spielen."], viewSound: "KLICK-KLACK"},
        {key: 'invManifest', title: 'Manifest', show: false, view: ["Aufruf zur ARBEITERREVOLUTION!!!", "Es werden besserer Arbeitsbedingungen für Mitarbeiter gefordert.", "Man kann mitmachen eine Gewerkschaft zu gründen."]},
        {key: 'invCatNotice', title: 'Mimi-Zettel', show: false, view: ["Katze Mimi ist entlaufen und wird gesucht.", "Der Zettel ist schon sehr alt." ,"Arme Katze Mimi"]},
        {key: 'invCoin', title: 'Münze', show: false, view: ["1 Bitcoin", "WOW", "Ich bin reich.", "Theoretisch."]},
        {key: 'invCokeOpen', title: 'Offene Cola', show: false, view: ["Die Flasche ist offen.", "Ich sollte sie sehr bald trinken."]},
        {key: 'invBottleOpener', title: 'Öffner', show: false, view: ["Damit öffnet man Flaschen."]},
        {key: 'invScrumGuide', title: 'Scrum Guide', show: false, view: ["Eine von Jeff Sutherland signierte Ausgabe des Scrum Guide."]},
        {key: 'invSprayCan', title: 'Spraydose', show: false, view: ["Ein Spraydose Farbe RAL 9016 - Verkehrsweiß."]},
        {key: 'invPen', title: 'Stift', show: false, view: ["Ein Permanentmarker.", "Bitte niemals auf Whiteboards benutzen."]},
        {key: 'invBusinessCards', title: 'Karten', show: false, view: ["Ein Stapel Visitenkarten.", "Die Rückseiten sind noch frei."]},
        {key: 'invAccessCard', title: 'Zugangskarte', show: false, view: ["Meine Eintrittskarte in die \"Welt der Träume.\"", "Sie öffnet den Aufzug."]},
    ],

    // Hilfsmethode zum Abrufen aller Assets für eine Szene
    getAssetsForScene(sceneKey) {
        const commonAssets = this.commonAssets || [];
        const sceneConfig = this.scenes[sceneKey] || {};
        const sceneAssets = sceneConfig.assets || [];

        return [...commonAssets, ...sceneAssets];
    }
};